language: node_js
node_js:
  - 12

env:
  global:
    secure: rEJQAigZpCZNjt0xc71uceh019vIO5jnDM/xnWPqeWU41uYaFVEnzwAmPFW7NAe8kN0wNrgKhDfFcN20dYI7AJ7xN/U3yMGg4hOoMY7vqF0cZ3tdogRYQKhe3pzrmPOytZAEoND7fP5B6oB4iD0v1vbmHRgTo90f5yICSaa3hBsx1cY33dUjlLIzWkHLK+NACyRbOGCmM0cfuI8dxt6O4Z1zU5K8fcJcfciJLSEyuWXLkphIdF87ptStpNtqnk58gyZQ/dWj8QzXwkdiniE3SUWoYEC7r1skttO0pQ+53/it5Euy53TcfhLHT3Ax5cdg8HTdr228t0TO2b4EiVT6146t2P85tSev1Wu7q7maUW/8IftV3OKz9bzOZ01yP1f37S2bE5pNWx1Ktxe3PBjPisBnyJR783AosYitnbchpV4Kt59YXczZl/je6ZUq3jYMtqW8o5EmHLX5QZUQA+U+AQinmAihwTD36pCPL4S5i6KBaL9oNBy1LP+48+VMyaeaQ3UlCJhO4Ve2jm44jvxyw3dyeG9AmGT0GHOORvH3XNw0MMykiPO1IIIMvO3UMAolvFknFV7QPpCqb4i06V9YUfqUsRzgud9i9WR+ve0GPiF4gXKp71DSv8Wit/I24BNATZP69UiyXeUmnm/xdC5ibzoZ6i9T5eu2++Zziei65kk=

script:
  #- npm run test-ci
  - npm run sonar
  - npm run build --prod

deploy:
  local_dir: ./dist/timeismoney
  skip_cleanup: true
  provider: pages
  repo: wiiitek/timeismoney.page
  target_branch: main
  fqdn: timeismoney.dev
  verbose: true
  keep_history: true
  on:
    branch: main
  github_token:
    secure: ZwIxE2QUG63kXdpFKQsNvJrldW1e3JU0gJMdPdJ9f30k8uajtorF9p6kkLp8SugAuLRvypMRYgrUZJfoEpUhkwCCc6fBTulGwW/Lt6YrHA4nCqLJf1tsEHbEhp6VXfiGcp3fe6wHUpWcnTaN6taFjYDeT+hRdV15P1rt+tGeR5lkSRPk3BNz6xzu9I95G7Clk4uhMy97GVMaid49Y7Z945vRWcnCP/RRw3GR8JflE7lYxV5gIiLlfsTs82vjiVjJAIMOkZ4y9voMRhkIR9fYTY+CKk9t6K4cKB9uRvU1dap9R7bBXunJIwkJ8gwTs+UEdv36pZjAt2BeGfG+pHZkubti5PHga+DGgd/x85vtu+qq618IAmvAimYgzI056/rXCoFw32mdeUkL5pNDUTNv1+OKZMwY1FxVk80aTBwzIsdJuxXaoKPWlsmQSPLjpjrM2xs7+DiWxrMPUVYfmSI6kgjhUFgBPlvZUckj4j4ZAgpOEL/Jw4WhSze0teppkoRN2dFUieAcubnR/WmCf0q32irHR+Ufo1AnsGwWDu0Hh21CLxddXEj4l7g1ip7fm9XeJkbb20cmjziHChLux/tC3JFn5ykzv/ss8utPgJ3zCZcAd03bc78ExqCb3uD7EdTOeOwiFP4AyO60OM8UTfKEBxOAowUaRcZ7badRvUH3gR4=
