language: node_js
node_js:
- 12

env:
  global:
    # for Sonar env variable
    secure: "W1CV1/Sf+obddqMxJVBqClBoLWv/kveWVhX/fEtWhIItSpUFgYaVsWkGgWHLoaNb3wmj36Gfd5TaZQ+DNG9nTMcgT2BVHeNTxeKrDce3noi7jeo555RI+Kvsysptw5KWxCXHTPpKMZIaN//VIYtdCBmA7acKR9XDmQ++Zps3nd1X1UYGlQoNDPbyT+oZ8byfp1UQ6yXyG6YNurA8V7oUXND5KBFwtwNfG8HFLy5LGuedzP+u/1oM7uxJZ/AcrZS4iPfzm8J911oXN4Raq37K2LgMZfhoX1w7caH/LucAlOBuMrHykgp+66UKMiBVGtiFXxWdK645d9VTB4VWpKL7+eji9Kt6EkkUmKcYPowFoQDCbk3zUGLoUxCJlyArmEorY10AbdYXs24ZOh85v569iBuLGXxqf1TRiFrNev0qvyIlSaOyRf6rPhdWp5OG7zMdcKPk8h0gBLPNyY7h4p9DoJdcoPKc6/XB3HLwwQQWNVk/cVUhD2yhr2on5LYOHLx6AFuT0cv7EF+VOMX3X/WtdSPprp2210cm9HSShiniR2iyQOkOGXOqDO5boLG9XN1tYAId4ymUCY8D/JTRt224SniTcBelTEnokT3Z1wHN04H7D9BnJT6wXpYwOf9+keJJbLDvqajGgvpSuKtfgosJn9jWR0oEibe5I7y9yOmvoF4="

script:
  - npm run test-ci
  - npm run sonar
  - npm run build --prod
