language: node_js
node_js:
  - 12
  - 15

sudo: true
dist: trusty

before_script:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script: 
  - ng test --watch false -cc
  - npm run e2e
