language: node_js
node_js:
- 12

env:
  global:
    # for Sonar env variable
    secure: "N7SScZhQ8nYAzLNtgIpGVFncBQVsbXlogrb6NZrOoymEp4vhmSVEi+wnVQWIvJ9bJihEOqQUvVeSE+oNdl8GGATapKAnO4KzBm5LGigOXFlOwgxeVw7GlOnSnsAlm29pgZfy47PVMhrMsvMclL3kU/MAKtWiAj6xhBExzwxG/C3EMUjU7Zifyj0yxPcpUmBm8A8O3RkzYBufbADckSVqbS20X5r6ZPwUsZcE59VAbfEYUTZuKFpWXDgIqjNiU0bV53LE/rAU5I7nIzwel61Fqtf5IKJ54s3/9zbHWWtxuZmmxGdYUTy47YyI/sJoDqIOp7b5cjNXZ1TJeNhP8ruzvk8pHhSCgNKQDIb/bIKY21UIjzgdncQ8Nn9nDm16C99gcZQKQKqqjlz5FZR6KRclyFHNMh3HlRbHmPfRl4K17D+jbBhMlY8o346fGqlKS7h0NryZt3q+HTVaZ93+LSx72b3VwKuYvNvKV1XMZ4zXsTQz013wEdJ0gsD/VPY6tG/pWCcdbuZsEjamHEXwEkW0MbnX7qKSr29QHVzNtSIym31X1cx3T6kRB1xLt9XjWa9nCNLyXSIJLzgdGRZi4rDXkkkmybjJW2BzsUNKmOMmQwOkCqlWlQVxzIZBJUY78MINKgd3UVyhbjqyNZe3if9IKxGIQRMhRrm2BST1TsUCH9E="

script:
  - npm run test-ci
  - npm run sonar
  - npm run build --prod
