dist: xenial
addons:
  chrome: stable
services:
  - xvfb

language: node_js
node_js:
  - 12
  - 15

before_install:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

script: 
  - ng test --watch false -cc
  - npm run e2e

