language: node_js

node_js:
  - 12

env:
  global:
    secure: rEJQAigZpCZNjt0xc71uceh019vIO5jnDM/xnWPqeWU41uYaFVEnzwAmPFW7NAe8kN0wNrgKhDfFcN20dYI7AJ7xN/U3yMGg4hOoMY7vqF0cZ3tdogRYQKhe3pzrmPOytZAEoND7fP5B6oB4iD0v1vbmHRgTo90f5yICSaa3hBsx1cY33dUjlLIzWkHLK+NACyRbOGCmM0cfuI8dxt6O4Z1zU5K8fcJcfciJLSEyuWXLkphIdF87ptStpNtqnk58gyZQ/dWj8QzXwkdiniE3SUWoYEC7r1skttO0pQ+53/it5Euy53TcfhLHT3Ax5cdg8HTdr228t0TO2b4EiVT6146t2P85tSev1Wu7q7maUW/8IftV3OKz9bzOZ01yP1f37S2bE5pNWx1Ktxe3PBjPisBnyJR783AosYitnbchpV4Kt59YXczZl/je6ZUq3jYMtqW8o5EmHLX5QZUQA+U+AQinmAihwTD36pCPL4S5i6KBaL9oNBy1LP+48+VMyaeaQ3UlCJhO4Ve2jm44jvxyw3dyeG9AmGT0GHOORvH3XNw0MMykiPO1IIIMvO3UMAolvFknFV7QPpCqb4i06V9YUfqUsRzgud9i9WR+ve0GPiF4gXKp71DSv8Wit/I24BNATZP69UiyXeUmnm/xdC5ibzoZ6i9T5eu2++Zziei65kk=

script:
  - npm run test-ci
  - npm run sonar
  - npm run build --prod

deploy:
  local_dir: ./dist
  provider: s3
  region: eu-west-1
  bucket: timeismoney.dev
  # https://docs.travis-ci.com/user/deployment-v2/providers/s3/#securing-secrets
  access_key_id:
    secure: FZ4eGhlHTmWet8xeJnEbPdApElwI5r7jbx1NuvMiK0x89+fKSMBofAX2yjw4mCHVxEZm8QoZtT7J6IkpGgZt9DNhRnlbUxjzZ+/TZNP3LwQ/xjThc5wOlLvJiYrvCGDNwTK69R5vWFNdcDI1Ev5psiER/3MFnxCyFBOuOQhBaN6koAQ05eAZ6wPkh3pK/10lz2ZC6DrFb+lz7BB4FadNHS4+5/QBTrfkiiqq4153tYuDzPH1oDiy0fIZ0i9pfrDu/+/ppP7GkNLWxjfOnLo74YlZ4qgkztjybenXEJSV22kirIsdXS6CzJCcw4jJc1Q1ZLyPwNCviwI+x0B/L/OrAVqtwx4Vq2OFlatfNp1/pPIYL75OOIGCKQCN9pzdjiQ9hLG/8MMPdmNF12uzELNqDVaiDhl/qNrNXSg9g+HJ5RmvMOUBNnLVPo5mV+Cq0dnUmDma16Amc0U4Z0Ser1bunSv4beHrfyH/7wr3+70LLVDOlo33xGsGcx1pEg68dCD1G/e3tNKHVdUiciM0T4g7raVsFYuyNDcvSrpqFk9j/u09dYTOZgfPXkQxeEbrpdXL6kRZU2bVX2OApzU1kzrW/4X3O6E0wxgDljz7sunqFOTWnMVcaGklbEBbWsJp8iYrrD3efQpjtfogiHycD41JfrOOW6l5UwDYJaT1ZkaxUwE=
  secret_access_key:
    secure: dUoTBTySijepMIvFjnVVFTLQRMRtu9qB4BCeEGMMI0ANwVkc9KHjChOEzY1DLVWTJ+1Lfzwxa+72ruF2EnDVQh1+MjaWoqAxHhZgjfckzeX5tBprPkpLiBJxz8qRxPcHos9VingYQjwL8HX9Z03P961tQzCyludaBprsRKqPjthVS+JQdcEMZuQ/HmdmPZaKdK25aPkumyWgko3sgEwcXzbu9FWE5lA8oHRyv2N1CMG6EiLs76twv2AYWXD21xoDD+gmHtXs96nf/IfDh+IX7hfoUkivTfrORcKWHuT/H24440HWMHW+rsGaPzHM8STYu7CrQRtiZFxdqBX1O8QvMFNAl2oET3lnMJ3u+R0dlJALWPthlq1R2H3WloN/3XrRPfeRxW3J5qUi/SjlZ2T3A1upSEG9rqrcApKoMiIGSSXm5rAuckl96cd9rH09vrTalFE3oFs9FfqodID3P7ozrYG6fuBXJRKQcUZhyGY14NsJWFardVZRyYwI4bL9WLKDCa6p9YisnXeTPKPgM29+AFxsdyn88xUtrcS/KkFRVRKLY1iiNi7uDlDj7nDQHp7v4Gwr55fyoH1YT5H/4GfieA/puoMe42tCCgGBUPptKInf/w65zLMe1SHjoIVNg3dxyQ3/FC/QunpXgWwMSkmew6iCn21+QJ4ZbIFNdtiGsKU=
  on:
    branch: main
