language: node_js
node_js:
- 12

# env:
#   global:
#     secure: ofDBgEtwmJg5QH+xfhC8YTy/d/KUsLOQNoRrfnEThdSktMxWYrMqa9QjWiHzT+lODiipbTfPjoGdHy6tgi+aegFdRRaVmnqPbkKFoTE9/5ibCmQfiRrY/7FIoIKn7HFqjomYF/89ITrsgguCtgtMG6Dbsug9kvpOQiw+VLxYJgu0+zHSu69mf9r5fECRJDibCEHPbKCE+8MQOtxtF+BlRIRD/QlN0PFsEYJfSYrNIZR8igF4BEgUulX/lH01EwlRrhvCrVIElYtVYVNhaF+jcpD1rZ1UHZWT1OAPa+PHd901mAtxOPBz3Bc1ecvxYMeA89HWzjR0qQcLfJECvFYR99AnFLMVa+ARgvjBFfN4ZFXMLR3VtrSvNdkwAfk7CxTeXumE8F0gkz77urPTFVviciE+yFxNHAgfp3iEFEyVbAWnWlU6kD9dHKH2Xxa99DZmC1MG6nWf0syLQo8HNOoAWagcSixCvk7RTF5UoOhpzWaTrQ7EGAvO8uVcsEBm/Q7qXyf6kXZI9pAnSYXOZ7o/IVXoXTy44aVg8hqSzUTvyLiBowsP/JCDHwZSpg+5N0b3xTVxCfyQ6jYOTRZQrdz9aW+qNPZV3dKK9GsKPgox/oQgUxK7ecraT5ylA92wC1JYfaG8ahKapER6NnYMx13wSSbNBlB8x4HOQJKMoX5OZME=

addons:
  sonarcloud:
    organization: wiiitek-github
    token:
      secure: ofDBgEtwmJg5QH+xfhC8YTy/d/KUsLOQNoRrfnEThdSktMxWYrMqa9QjWiHzT+lODiipbTfPjoGdHy6tgi+aegFdRRaVmnqPbkKFoTE9/5ibCmQfiRrY/7FIoIKn7HFqjomYF/89ITrsgguCtgtMG6Dbsug9kvpOQiw+VLxYJgu0+zHSu69mf9r5fECRJDibCEHPbKCE+8MQOtxtF+BlRIRD/QlN0PFsEYJfSYrNIZR8igF4BEgUulX/lH01EwlRrhvCrVIElYtVYVNhaF+jcpD1rZ1UHZWT1OAPa+PHd901mAtxOPBz3Bc1ecvxYMeA89HWzjR0qQcLfJECvFYR99AnFLMVa+ARgvjBFfN4ZFXMLR3VtrSvNdkwAfk7CxTeXumE8F0gkz77urPTFVviciE+yFxNHAgfp3iEFEyVbAWnWlU6kD9dHKH2Xxa99DZmC1MG6nWf0syLQo8HNOoAWagcSixCvk7RTF5UoOhpzWaTrQ7EGAvO8uVcsEBm/Q7qXyf6kXZI9pAnSYXOZ7o/IVXoXTy44aVg8hqSzUTvyLiBowsP/JCDHwZSpg+5N0b3xTVxCfyQ6jYOTRZQrdz9aW+qNPZV3dKK9GsKPgox/oQgUxK7ecraT5ylA92wC1JYfaG8ahKapER6NnYMx13wSSbNBlB8x4HOQJKMoX5OZME=

script:
  - npm run test-ci
  - npm run sonar
  - npm run build --prod
