language: node_js
node_js:
- 12

env:
  global:
    # for Sonar env variable
    secure: "I543/AR1IIvKDbV/JHC6xxDu4mqfJ8bSRsBqPzEcpGP1BkqhWHq+XCFygi69Qa1On58GLY7K1BYMUUbbBuFcv9zMbrsf8mKOhsnZ+Gzw9TR5/j6K5etfWW41oBsq7aSpMf3OXTftdUoI5C3/g+KVrnczbv5fi4TqMsfZX8IoF01kPy6lqhqOMASMM0vLh5N2l9vsjXDlCgnDiTAHZ12/lkRwyulsAGmeNfo761KkF/Ut6MRegVkcS5prf/9VissqBUD5OnS6beASjwwqV2eOPkp/9faSOd/++jXFCRS9wU9iPzkaW8p81bGvGvvXAXKtU3rORr0vMWaDLZgF3rgTZEPyGZD+KMgDbTNNWyfCscpSwc70JjC7J/VLHk1Vo4eu+5/w0sjTGSFmB/id1aky/gNxDlOb45uMS4xz9q9f7r+bTkIaIlb/HTwFwsE38UIXKXOX6iglhUP804v5lHUHfquNxj9qqsM53RpgEd1RMM5u4Wkl5xX6SQ1911B9k/DyijD11qAM0Ayl6gPrjm60cL3Xwi4Mz2ADTNsdt6cfSQZ6ZzWz0VDV2+vXRLu3pFcfWCaNIhCk5nFNigYA/BI5zEiK+oUC7YVP0CC4uL3WzPFyXRsWYiw9feJuPx+/83mPQz3rz/6mfMS2dKIIj2VxVYsk3WqkiTHnoAokoOm/g2w="

script:
  - npm run test-ci
  - npm run sonar
  - npm run build --prod
