name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # https://github.com/marketplace/actions/yarn-node-install-cache
      - uses: egordm/gha-yarn-node-cache@v1

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and npm run build
        run: |
          yarn install
          yarn test
          yarn sonar
          yarn build
