name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and npm run build
        run: |
          npm ci
          npm run test
          npm run sonar
          npm run build
