name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # https://github.com/marketplace/actions/yarn-node-install-cache
      - uses: egordm/gha-yarn-node-cache@v1

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          yarn lint
          yarn install
          yarn test
          yarn sonar

      - name: Build
        run: |
          yarn build

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        # https://github.com/JamesIves/github-pages-deploy-action#configuration-
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          repository-name: wiiitek/timeismoney.page
          branch: main
          folder: dist/timeismoney
          token: ${{ secrets.GH_TOKEN }}
