name: GitHub Page Updated

on:
  push:
    branches:
      - gh-pages

jobs:
  debug-message:
    name: Show debug message about gh-pages branch
    runs-on: ubuntu-latest

    steps:
      - name: Show Info
        run: 'echo "GITHUB_REF: ${GITHUB_REF}, GITHUB_SHA: ${GITHUB_SHA}"'
